apiVersion: v1
kind: Service
metadata:
  name: {{ include "topolsea.fullname" . }}
  labels:
    app: topolsea
spec:
  type: {{ .Values.service.type }}
  selector:
    app: topolsea
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      name: http
{{- if .Values.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "topolsea.fullname" . }}-data
spec:
  accessModes: ["ReadWriteOnce"]
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
