[package]
name = "dv-index-ivf"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
dv-index-api = { path = "../dv-index-api" }
dv-metrics = { path = "../dv-metrics" }
dv-topk = { path = "../dv-topk" }
dv-types = { path = "../dv-types" }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
approx = { workspace = true }
tempfile = { workspace = true }
